server:
  port: 8083

spring:
  application:    name: API_GATEWAY  cloud:    gateway:       routes:        - id: COMPANY-SERVICE
          uri:            lb://COMPANY-SERVICE
          predicates:
          - Path=/api/v1.0/company/**
        - id: STOCK-SERVICE
          uri:
            lb://STOCK-SERVICE
          predicates:
          - Path=/api/v1.0/stock/**
          
                                         